spring.application.name=mapNotifier

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/google_map_notifier
spring.datasource.username=gmn_user
spring.datasource.password=gmn_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080